export const addSearchCriteria = 'ADD_SEARCH_CRITERIA'
export const deleteSearchCriteria = 'DELETE_SEARCH_CRITERIA'

export const changeName = 'CHANGE_NAME'
export const changeNickname = 'CHANGE_NICKNAME'
export const changeEmail = 'CHANGE_EMAIL'
export const changeCountry = 'CHANGE_COUNTRY'
export const changeContentType = 'CHANGE_CONTENT-TYPE'
export const changePassword = 'CHANGE_PASSWORD'

export const LoginProfileName = 'LOGIN_PROFILE_NAME'
export const LoginProfileNickname = 'LOGIN_PROFILE_NICKNAME'
export const LoginProfileEmail = 'LOGIN_PROFILE_EMAIL'
export const LoginProfileCountry = 'LOGIN_PROFILE_COUNTRY'
export const LoginProfileContentType = 'LOGIN_PROFILE_CONTENT-TYPE'
export const LoginProfilePlatforms = 'LOGIN_PROFILE_PLATFORMS'
export const LoginProfileID = 'LOGIN_PROFILE_ID'
export const LoginProfileLogged = 'LOGIN_PROFILE_LOGGED'
export const Logout = 'LOGOUT'